#!/bin/bash
# compile varRhoIncompressible class
cd varRhoIncompressible

wmake

cd ..


#compile varRhoInterFoam family

#varRhoInterFoam
cd varRhoInterFoam

wmake

#varRhoInterDyMFoam
cd varRhoInterDyMFoam

wmake

cd ..

#varRhoInterMixingFoam
cd varRhoInterMixingFoam

wmake

cd ..

cd ..


#compile varRhoMultiphaseInterFoam family

cd varRhoMultiphaseInterFoam

# multiphaseMixture
cd multiphaseMixture

wmake

cd ..

# varRhoMultiphaseInterFoam
wmake

# varRhoMultiphaseInterDyMFoam
cd varRhoMultiphaseInterDyMFoam

wmake

cd ..

cd ..


#compile varRhoInterPhaseChangeFoam family
cd varRhoInterPhaseChangeFoam

# phaseChangeTwoPhaseMixtures
cd phaseChangeTwoPhaseMixtures
wmake
cd ..

# varRhoInterPhaseChangeDyMFoam
cd varRhoInterPhaseChangeDyMFoam
wmake
cd ..

# varRhoInterPhaseChangeFoam
wmake

cd ..
