#!/bin/bash
# compile varRhoIncompressible class
cd varRhoIncompressible

wmake

cd ..


#compile varRhoInterFoam family

#varRhoInterFoam
cd varRhoInterFoam

wmake

#varRhoInterMixingFoam
cd varRhoInterMixingFoam

wmake

cd ..

cd ..


#compile varRhoMultiphaseInterFoam family

cd varRhoMultiphaseInterFoam

# multiphaseMixture
cd multiphaseMixture

wmake

cd ..

# varRhoMultiphaseInterFoam
wmake


cd ..



